<style>
table { 
	width: 600px; 
	border-collapse: collapse; 
	margin:30px auto;
	}
tr:nth-of-type(odd) { 
	background: #eee; 
	}

th { 
	background: #3498db; 
	color: white; 
	font-weight: bold; 
	}

td, th { 
	padding: 10px; 
	border: 1px solid #ccc; 
	text-align: left; 
	font-size: 18px;
	}
@media 
only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1024px)  {

	table { 
	  	width: 100%; 
	}
	table, thead, tbody, th, td, tr { 
		display: block; 
	}
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	
	tr { border: 1px solid #ccc; }
	
	td { 
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
	}

	td:before { 
		position: absolute;
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
		content: attr(data-column);

		color: #000;
		font-weight: bold;
	}

}
</style>
        <div class="col-12">
            <h3>My Playlists</h3>
            <table class="table table-image">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <form action="/spotify/removeTrack" method="post">
                        <?php foreach($playlists['items'] as $key => $value) {
                            echo "<tr>
                                <td>".$key."</td>
                                <td>".$value['track']['album']['name']."</td>
                                <td><button class='btn btn-success' type='submit' name='removeTrack' value=".$value['track']['uri'].">Remove</button></td>
                            </tr>
                            <input type='hidden' name='playlist_id' value=".$_GET['id'].">";
                        }
                        ?>
                    </form>
                </tbody>
            </table>
        </div>
  

